-- MySQL Script generated by MySQL Workbench
-- Mon 06 Feb 2023 08:31:24 PM PST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cities` (
  `city_id` INT NOT NULL AUTO_INCREMENT,
  `city_name` VARCHAR(80) NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`city_id`),
  UNIQUE INDEX `city_name_UNIQUE` (`city_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Homes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Homes` (
  `home_id` INT NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(80) NOT NULL,
  `sq_ft` INT(10) NOT NULL,
  `num_of_bed` INT(10) NOT NULL,
  `num_of_bath` INT(10) NOT NULL,
  `year_built` INT(4) NOT NULL,
  `lat` DECIMAL(6,3) NOT NULL,
  `lng` DECIMAL(6,3) NOT NULL,
  `zip` VARCHAR(45) NOT NULL,
  `city_id` INT NOT NULL,
  PRIMARY KEY (`home_id`, `city_id`),
  INDEX `city_id` (`city_id` ASC) VISIBLE,
  CONSTRAINT `city_id`
    FOREIGN KEY (`city_id`)
    REFERENCES `mydb`.`Cities` (`city_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Region_Statistics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Region_Statistics` (
  `region_statistic_id` INT NOT NULL AUTO_INCREMENT,
  `region_name` VARCHAR(80) NULL,
  `location_description` VARCHAR(180) NOT NULL,
  `avg_price_per_sq_ft` DECIMAL(10,2) NOT NULL,
  `mean_housing_price` DECIMAL(10,2) NOT NULL,
  `five_year_price_gradient` DECIMAL(10,3) NOT NULL,
  `ten_year_price_gradient` DECIMAL(10,3) NOT NULL,
  `median_housing_price` DECIMAL(10,2) NOT NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`region_statistic_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Zillow_Estimates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Zillow_Estimates` (
  `zillow_price_id` INT NOT NULL AUTO_INCREMENT,
  `zestimate` DECIMAL(10,2) NOT NULL,
  `date` DATE NOT NULL,
  `home_id` INT NOT NULL,
  PRIMARY KEY (`zillow_price_id`, `home_id`),
  INDEX `home_id` (`home_id` ASC) VISIBLE,
  CONSTRAINT `fk_Zillow_Estimates_Homes1`
    FOREIGN KEY (`home_id`)
    REFERENCES `mydb`.`Homes` (`home_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Region_Statistics_has_Cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Region_Statistics_has_Cities` (
  `region_statistics_has_cities_id` INT NOT NULL AUTO_INCREMENT,
  `city_id` INT NOT NULL,
  `region_statistic_id` INT NOT NULL,
  PRIMARY KEY (`region_statistics_has_cities_id`, `city_id`, `region_statistic_id`),
  INDEX `city_id` (`city_id` ASC) VISIBLE,
  INDEX `region_statistic_id` (`region_statistic_id` ASC) VISIBLE,
  CONSTRAINT `city_id`
    FOREIGN KEY (`city_id`)
    REFERENCES `mydb`.`Cities` (`city_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `region_statistic_id`
    FOREIGN KEY (`region_statistic_id`)
    REFERENCES `mydb`.`Region_Statistics` (`region_statistic_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
